# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: "#home"
    weight: 10
  - name: About
    url: "#about"
    weight: 20
  - name: Projects
    url: "#projects"
    weight: 25
  - name: ğŸ“š Guides & Resources
    url: "#guides"
    weight: 30
  - name: ğŸ™‹ Community & Network
    url: "#community"
    weight: 30
  - name: ğŸ“ Blog
    url: "#blog"
    weight: 40
  - name: ğŸ’š Members
    url: "#members"
    weight: 50
  - name: ğŸ¤ Associates
    url: "#associates"
    weight: 60
  - name: ğŸ‘‹ Join
    url: "#join"
    weight: 70
  - name: ğŸ’¬ Q&A
    url: "#faq"
    weight: 80
